### ISSUE TITLE
회원가입 기능

### ISSUE THREAD

**Issue by Invidam** [BCSDLab/JJBAKSA_BACK_END#85]
## Description

회원가입과, 이를 위해 필요한 기타 기능들
## Task List

- [x] 회원가입 API
  - #7
  - #29
- [x] 이메일 발송 API
  - #61
- [x] 이메일 인증 API
  - #61
  - [ ] 인증 완료 시 닉네임 수정 페이지로 이동 (동적 링크)
- [x] 아이디 중복 확인
  - #45

## Remark

- 이메일 템플릿이 없음.
- 인증 시 닉네임 수정 페이지 or App과의 연결 필요
- **Q: 닉네임 입력 API가 있는지??**

**Comment by insukL** [comment]
닉네임 수정, 비밀번호 수정의 경우 PATCH /user/me (modify user)에 포함되어 있습니다.

아이디 수정는 2차 배포 시 수정하겠습니다.
