### ISSUE TITLE
핀에 있는 상점 보기

### ISSUE THREAD

**Issue by Invidam** [BCSDLab/JJBAKSA_BACK_END#89]
## Description

핀을 통하여 상점 정보를 조회

## Task List

- [x] 상점 정보 반환
  - [x] 상점 이름, 분류, 별점, 상점 현재 영업 여부
  - [x] 북마크 여부, 내 마지막 리뷰 작성 시간
- [x] 상점 이미지 표시 (구글 이미지)
  - 최대 10개

## Remark

- 참고
  - #15
  - #43
  - #60
- 리뷰에 대한 내용은 #90 으로 넘겼음.
