### ISSUE TITLE
상점 검색 기능

### ISSUE THREAD

**Issue by Invidam** [BCSDLab/JJBAKSA_BACK_END#91]
## Description

메인페이지, 리뷰하기, 상점 검색, 북마크한 상점 보기에서 각각 활용하는 상점 검색 기능

메인페이지
![image](https://github.com/BCSDLab/JJBAKSA_BACK_END/assets/71889359/f87b5e8a-2f7f-4f21-972b-7305b7c03d3b)

리뷰하기
![image](https://github.com/BCSDLab/JJBAKSA_BACK_END/assets/71889359/0d308587-134d-47de-99a7-093c802d31df)

상점 검색
![image](https://github.com/BCSDLab/JJBAKSA_BACK_END/assets/71889359/5e6582af-3ef9-45aa-9f8f-e5f5cbb6a427)

북마크한 상점
![Image](https://github.com/BCSDLab/JJBAKSA_BACK_END/assets/71889359/904dc304-24a6-45a2-a21e-a62e4364d3cf)

### 각각의 차이점
|특징|메인페이지|리뷰하기|상점 검색|북마크한 상점|
|---|---|---|---|---|
|검색 목표| 근처 상점 조회 | 리뷰 | 검색| 북마크를 이용 |
|검색 조건| 현재 지명(동남구 병천면) | 검색 키워드 + 좌표 | 검색 키워드 + 좌표| 북마크 여부|
|검색 결과 특이사항| 영업 종료 시간을 전달 | X  | 이미지 목록을 전달| 이미지 목록을 전달|

## Task List

- [ ] ~~#105~~
  - [ ] ~~지형 기반 조회된 상점의 수~~
  - [ ] ~~상점 정보 (상점이름, 상점 이미지, 상점 카테고리, 상점 위치, 남은 거리, 별점,  영업 여부,  영업 종료 시간)~~
- [x] 리뷰하기 검색
  - [ ] ~~검색어 기반 조회된 상점의 수~~
  - [x] 상점 정보 (상점이름, 상점 이미지, 상점 카테고리, 상점 위치, 남은 거리, 별점,  영업 여부,  영업 종료 시간)
- [x] 상점 검색
  - [ ] ~~검색어 기반 조회된 상점의 수~~
  - [x] 상점 정보 (상점이름, 상점 이미지 **목록**, 상점 카테고리, 상점 위치, 남은 거리, 별점,  영업 여부,  영업 종료 시간)
- [x] 북마크한 상점
  - [ ] ~~북마크한 상점의 수~~
  - [x] 상점 정보 (상점이름, 상점 이미지 **목록**, 상점 카테고리, 별점)

## Remark

- 모두 구글 이미지를 사용
- 백엔드에서 셋 다 같은 API로 처리할 수 있지 않을까요?
- `상점 검색`의 결과에도 영업 종료 시간이 필요하지 않을까요?

**Comment by Yoojkim** [comment]
+) 메인페이지 검색은 사용하지 않는다고 하셨습니다. (figma 005_04)

조회된 상점 수 <- 구글 API에서 애초에 페이지네이션 되어 나오기 때문에 제공 불가능합니다.
