### ISSUE TITLE
상점 상세 정보 기능

### ISSUE THREAD

**Issue by Invidam** [BCSDLab/JJBAKSA_BACK_END#92]
## Description

상점에 대한 상세 정보를 제공한다.
## Task List

- [x] 상점 기본 정보
  - [x] 식당 명, 카테고리, 별점
  - [x] 위치, 전화번호, 영업 시간
  - [x] 북마크 여부
  - [x] 좌표

## Remark

- #60
- 리뷰도 함께 제공이 되어야 합니다. 클라이언트에서 단일 상점 API와 함께 해당 상점에 대한 리뷰 목록 API를 호출하는 방식으로 계획하고 계신가요?
- #90
