### ISSUE TITLE
프로필 페이지 기능

### ISSUE THREAD

**Issue by Invidam** [BCSDLab/JJBAKSA_BACK_END#93]
## Description

마이페이지를 위한 기능 목록
## Task List

- [x] 사용자 정보
  - [x] 사용자(나, 다른 사용자) 정보 조회 (이미지 이름 아이디 팔로워 수)
  - [x] (나) 프로필 변경 (이미지, 닉네임)
- [x] 사용자가 작성한 리뷰
  - #90 에 포함
- [x] 사용자가 북마크한 상점 개수, 목록
  -  #91 에 포함

## Remark

- (추후 추가) 다른 사용자의 북마크는 친구 여부에 따라 보여주기를 결정할 수 있다.
