### ISSUE TITLE
친구 기능 (+사용자 검색)

### ISSUE THREAD

**Issue by Invidam** [BCSDLab/JJBAKSA_BACK_END#94]
## Description

친구 추가, 검색, 신청 등에 대한 기능 목록이다.

## Task List

- [x] 사용자 목록
  - [x] 친구 목록
    - [x] 최근 활동 친구 목록 (마지막 로그인 날짜가 12시간 이내)
    - [x] 모든 친구 목록 
      - [ ] 새로 친구가 된지 2일 이내면 `new` 를 표기하기 위한 정보 제공

  - [x] 검색한 사용자 목록 
- [x] 친구 관리
  - [x] 친구 신청
  - [x] 친구 신청 수락 / 거절
  - [x] 친구 언팔 / 언팔 취소

## Remark

- 참고
  - #11
    - #14
    - #17
- 새로 친구가 된지 2일 이내면 `new` 를 표기하기 위한 정보 제공을 추후로 미뤄도 될까요?
- 친구, 팔로우 용어 통일이 필요할 듯
- (추후) 최근에 게시글을 올렸고, 내가 해당 게시글을 확인하지 않은 친구에게 주황 점을 표기하기 위한 정보 제공
