### ISSUE TITLE
사용자 설정

### ISSUE THREAD

**Issue by Invidam** [BCSDLab/JJBAKSA_BACK_END#95]
## Description

사용자 정보 수정, 서비스 탈퇴 등을 포함하는 기능 목록이다.

## Task List

- [x] 비밀번호 변경
- [x] 회원 탈퇴 요청
  - [x] 탈퇴 사유 (라디오 버튼) {변경 사유}
  - [x] 탈퇴 사유 (텍스트) {개선 사항}
- [x] 회원 탈퇴 프로세스
  - [x] 즉시 삭제: 게시글, **리뷰 정보, 제공한 사진**, 북마크 음식점, 친구 목록, **남긴 별점**, 검색 기록, 활동 내역, 팔로우 정보, 문의 내역, 신고당한 내역, 친구 신청 내역
  - [x] 일주일 이후 삭제: 재가입 방지 위한 이메일, SNS 인증 정보, ID, PW
  - [x] 삭제 X : 신고한 내역
  - 참고: https://bcsdlab.slack.com/archives/C0397CS4R4P/p1684854955648459

## Remark

- 참고
  -  #67
  -  #79
- 리뷰 정보, 제공한 사진은 굳이 삭제를 안해도 되지 않을까요?

**Comment by insukL** [comment]
UI/UX에서 말하는 삭제랑 우리가 말하는 DB예서 삭제가 다를 것으로 보입니다.

DB는 로그의 기능을 겸하기 때문에 무계획적인 영구 삭제를 안될 것으로 보입니다.
개인 정보와 직접적으로 관련된 내용은 데이터를 수정하거나 정규화를 통해 영구 삭제할 내용을 분리해야할 필요가 보입니다.

그리고 여기에 UI/UX는 약관이 직접적으로 관련되어 있을 것 같아 조율이 필요해 보입니다.
